
const STATUS_OK = 200;
const STATUS_CREATED = 201;
const ERROR_BAD_REQUEST = 400;
const ERROR_BAD_DATA = 401;
const ERROR_NOT_FOUND = 404;
const ERROR_EXISTS = 409;
const ERROR_SERVER = 500;

module.exports = {
  STATUS_OK,
  STATUS_CREATED,
  ERROR_BAD_REQUEST,
  ERROR_BAD_DATA,
  ERROR_NOT_FOUND,
  ERROR_EXISTS,
  ERROR_SERVER,
};
